name: My CI-CD 
on:
  push: 
    branches: [develop]
jobs: 
  build: 
    runs-on: ubuntu-latest
   
    steps: 
      — uses: actions/checkout@v2 
      — run: | 
          cd my-express-app && pwd
          npm i