name: My CI-CD 
on:
  push: 
    branches: [develop]
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: install package
      run: |
        cd /var/www/vue-project && pwd
        npm i

      